apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: my-app-image-stream
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/redhattraining/hello-world-nginx:v1.0
    importPolicy:
      scheduled: true
