apiVersion: apps/v1  
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: labs
  labels:
    app: myapp
spec:  
  replicas: 2  
  selector:
    matchLabels:
      app: myapp
      type: front-end
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec: 
      containers:
      - name: my-container
        image: nginx:1.71 # choose one that is not deprecated version of nginx
